### ISSUE TITLE
Question: Would another wildcard setting be an option?

### ISSUE THREAD

**Issue by marijoo** [Namoshek/laravel-scout-database#47]
First of all: great package for medium sized projects needing a search index that goes beyond the default Scout database driver. Thanks!

I wonder what you think about another configurable option that would make the `SearchConfiguration` tweakable similar to the `lastTokenShouldUseWildcard()` setting. I’m thinking about implementing something like this:

```php
if ($this->searchConfiguration->allTokensShouldUseWildcard()) {
    $keywords = array_map(fn($token) => "%{$token}%", $keywords);
}
```

Do you think this is reasonable? Would you accept a PR for this?

Reason is I would like to match the following words with the query `entgelt` where now only the last two are found:

- Basisentgelt
- Serviceentgelt
- Entgelt A
- Entgelt B

**Comment by Namoshek** [comment]
I wouldn't mind such a feature in the library, even though I wouldn't use it personally due to performance concerns (haven't tested it though). Maybe this could or should be combined with some kind of minimum length per keyword (see code) to prevent searches for too short strings like `e` or `ent`?

```php
if ($this->searchConfiguration->allTokensShouldUseWildcard()) {
    $keywords = array_map(
        fn ($token) => mb_strlen($token) >= $this->searchConfiguration->minimumLengthForWildcard() ? "%{$token}%" : $token,
        $keywords
    );
}
```

---

A few things to keep in mind regarding the implementation:

- There is this part that needs revisiting if this is implemented:
https://github.com/Namoshek/laravel-scout-database/blob/83d0ce9f8ac99630c869a0fabaae77a547fb8c01/src/DatabaseSeeker.php#L157

- Regarding the `require_match_for_all_tokens` option, I'm not sure what to do. On the one side, I think using it in combination with the option suggested by you is rather stupid. On the other hand, adding some additional logic at runtime seems a bad idea too. So I guess the only viable option would be a safeguard that prevents using them together, or at least adding some kind of warning in the config file?
https://github.com/Namoshek/laravel-scout-database/blob/83d0ce9f8ac99630c869a0fabaae77a547fb8c01/config/scout-database.php#L170-L192
https://github.com/Namoshek/laravel-scout-database/blob/83d0ce9f8ac99630c869a0fabaae77a547fb8c01/src/DatabaseSeeker.php#L204-L207

- Depending on the remaining logic, the new option should be mutual exclusive or at least be safe to be used in combination with:
https://github.com/Namoshek/laravel-scout-database/blob/83d0ce9f8ac99630c869a0fabaae77a547fb8c01/src/DatabaseSeeker.php#L79-L81
